-- Seed all 543 Lok Sabha Constituencies of India
-- Clears previous demo data to prevent duplicate primary keys
TRUNCATE TABLE constituencies CASCADE;

INSERT INTO constituencies (id, name, state, mp_name, mp_user_id) VALUES
-- Andhra Pradesh (25)
('AP-01', 'Araku', 'Andhra Pradesh', 'Hon. Representative', ''),
('AP-02', 'Srikakulam', 'Andhra Pradesh', 'Hon. Representative', ''),
('AP-03', 'Vizianagaram', 'Andhra Pradesh', 'Hon. Representative', ''),
('AP-04', 'Visakhapatnam', 'Andhra Pradesh', 'Hon. Representative', ''),
('AP-05', 'Anakapalli', 'Andhra Pradesh', 'Hon. Representative', ''),
('AP-06', 'Kakinada', 'Andhra Pradesh', 'Hon. Representative', ''),
('AP-07', 'Amalapuram', 'Andhra Pradesh', 'Hon. Representative', ''),
('AP-08', 'Rajahmundry', 'Andhra Pradesh', 'Hon. Representative', ''),
('AP-09', 'Narasapuram', 'Andhra Pradesh', 'Hon. Representative', ''),
('AP-10', 'Eluru', 'Andhra Pradesh', 'Hon. Representative', ''),
('AP-11', 'Machilipatnam', 'Andhra Pradesh', 'Hon. Representative', ''),
('AP-12', 'Vijayawada', 'Andhra Pradesh', 'Hon. Representative', ''),
('AP-13', 'Guntur', 'Andhra Pradesh', 'Hon. Representative', ''),
('AP-14', 'Narasaraopet', 'Andhra Pradesh', 'Hon. Representative', ''),
('AP-15', 'Bapatla', 'Andhra Pradesh', 'Hon. Representative', ''),
('AP-16', 'Ongole', 'Andhra Pradesh', 'Hon. Representative', ''),
('AP-17', 'Nandyal', 'Andhra Pradesh', 'Hon. Representative', ''),
('AP-18', 'Kurnool', 'Andhra Pradesh', 'Hon. Representative', ''),
('AP-19', 'Anantapur', 'Andhra Pradesh', 'Hon. Representative', ''),
('AP-20', 'Hindupur', 'Andhra Pradesh', 'Hon. Representative', ''),
('AP-21', 'Kadapa', 'Andhra Pradesh', 'Hon. Representative', ''),
('AP-22', 'Nellore', 'Andhra Pradesh', 'Hon. Representative', ''),
('AP-23', 'Tirupati', 'Andhra Pradesh', 'Hon. Representative', ''),
('AP-24', 'Rajampet', 'Andhra Pradesh', 'Hon. Representative', ''),
('AP-25', 'Chittoor', 'Andhra Pradesh', 'Hon. Representative', ''),

-- Arunachal Pradesh (2)
('AR-01', 'Arunachal West', 'Arunachal Pradesh', 'Hon. Representative', ''),
('AR-02', 'Arunachal East', 'Arunachal Pradesh', 'Hon. Representative', ''),

-- Assam (14)
('AS-01', 'Kokrajhar', 'Assam', 'Hon. Representative', ''),
('AS-02', 'Dhubri', 'Assam', 'Hon. Representative', ''),
('AS-03', 'Barpeta', 'Assam', 'Hon. Representative', ''),
('AS-04', 'Darrang-Udalguri', 'Assam', 'Hon. Representative', ''),
('AS-05', 'Guwahati', 'Assam', 'Hon. Representative', ''),
('AS-06', 'Diphu', 'Assam', 'Hon. Representative', ''),
('AS-07', 'Karimganj', 'Assam', 'Hon. Representative', ''),
('AS-08', 'Silchar', 'Assam', 'Hon. Representative', ''),
('AS-09', 'Nagaon', 'Assam', 'Hon. Representative', ''),
('AS-10', 'Kaziranga', 'Assam', 'Hon. Representative', ''),
('AS-11', 'Sonitpur', 'Assam', 'Hon. Representative', ''),
('AS-12', 'Lakhimpur', 'Assam', 'Hon. Representative', ''),
('AS-13', 'Dibrugarh', 'Assam', 'Hon. Representative', ''),
('AS-14', 'Jorhat', 'Assam', 'Hon. Representative', ''),

-- Bihar (40)
('BR-01', 'Valmiki Nagar', 'Bihar', 'Hon. Representative', ''),
('BR-02', 'Paschim Champaran', 'Bihar', 'Hon. Representative', ''),
('BR-03', 'Purvi Champaran', 'Bihar', 'Hon. Representative', ''),
('BR-04', 'Sheohar', 'Bihar', 'Hon. Representative', ''),
('BR-05', 'Sitamarhi', 'Bihar', 'Hon. Representative', ''),
('BR-06', 'Madhubani', 'Bihar', 'Hon. Representative', ''),
('BR-07', 'Jhanjharpur', 'Bihar', 'Hon. Representative', ''),
('BR-08', 'Supaul', 'Bihar', 'Hon. Representative', ''),
('BR-09', 'Araria', 'Bihar', 'Hon. Representative', ''),
('BR-10', 'Kishanganj', 'Bihar', 'Hon. Representative', ''),
('BR-11', 'Katihar', 'Bihar', 'Hon. Representative', ''),
('BR-12', 'Purnia', 'Bihar', 'Hon. Representative', ''),
('BR-13', 'Madhepura', 'Bihar', 'Hon. Representative', ''),
('BR-14', 'Araria', 'Bihar', 'Hon. Representative', ''),
('BR-15', 'Darbhanga', 'Bihar', 'Hon. Representative', ''),
('BR-16', 'Muzaffarpur', 'Bihar', 'Hon. Representative', ''),
('BR-17', 'Vaishali', 'Bihar', 'Hon. Representative', ''),
('BR-18', 'Gopalganj', 'Bihar', 'Hon. Representative', ''),
('BR-19', 'Siwan', 'Bihar', 'Hon. Representative', ''),
('BR-20', 'Maharajganj', 'Bihar', 'Hon. Representative', ''),
('BR-21', 'Saran', 'Bihar', 'Hon. Representative', ''),
('BR-22', 'Hajipur', 'Bihar', 'Hon. Representative', ''),
('BR-23', 'Ujiarpur', 'Bihar', 'Hon. Representative', ''),
('BR-24', 'Samastipur', 'Bihar', 'Hon. Representative', ''),
('BR-25', 'Begusarai', 'Bihar', 'Hon. Representative', ''),
('BR-26', 'Khagaria', 'Bihar', 'Hon. Representative', ''),
('BR-27', 'Bhagalpur', 'Bihar', 'Hon. Representative', ''),
('BR-28', 'Banka', 'Bihar', 'Hon. Representative', ''),
('BR-29', 'Munger', 'Bihar', 'Hon. Representative', ''),
('BR-30', 'Nalanda', 'Bihar', 'Hon. Representative', ''),
('BR-31', 'Patna Sahib', 'Bihar', 'Hon. Representative', ''),
('BR-32', 'Pataliputra', 'Bihar', 'Hon. Representative', ''),
('BR-33', 'Arrah', 'Bihar', 'Hon. Representative', ''),
('BR-34', 'Buxar', 'Bihar', 'Hon. Representative', ''),
('BR-35', 'Sasaram', 'Bihar', 'Hon. Representative', ''),
('BR-36', 'Karakat', 'Bihar', 'Hon. Representative', ''),
('BR-37', 'Jahanabad', 'Bihar', 'Hon. Representative', ''),
('BR-38', 'Aurangabad', 'Bihar', 'Hon. Representative', ''),
('BR-39', 'Gaya', 'Bihar', 'Hon. Representative', ''),
('BR-40', 'Jamui', 'Bihar', 'Hon. Representative', ''),

-- Chhattisgarh (11)
('CG-01', 'Sarguja', 'Chhattisgarh', 'Hon. Representative', ''),
('CG-02', 'Raigarh', 'Chhattisgarh', 'Hon. Representative', ''),
('CG-03', 'Janjgir-Champa', 'Chhattisgarh', 'Hon. Representative', ''),
('CG-04', 'Korba', 'Chhattisgarh', 'Hon. Representative', ''),
('CG-05', 'Bilaspur', 'Chhattisgarh', 'Hon. Representative', ''),
('CG-06', 'Rajnandgaon', 'Chhattisgarh', 'Hon. Representative', ''),
('CG-07', 'Durg', 'Chhattisgarh', 'Hon. Representative', ''),
('CG-08', 'Raipur', 'Chhattisgarh', 'Hon. Representative', ''),
('CG-09', 'Mahasamund', 'Chhattisgarh', 'Hon. Representative', ''),
('CG-10', 'Bastar', 'Chhattisgarh', 'Hon. Representative', ''),
('CG-11', 'Kanker', 'Chhattisgarh', 'Hon. Representative', ''),

-- Goa (2)
('GA-01', 'North Goa', 'Goa', 'Hon. Representative', ''),
('GA-02', 'South Goa', 'Goa', 'Hon. Representative', ''),

-- Gujarat (26)
('GJ-01', 'Kachchh', 'Gujarat', 'Hon. Representative', ''),
('GJ-02', 'Banaskantha', 'Gujarat', 'Hon. Representative', ''),
('GJ-03', 'Patan', 'Gujarat', 'Hon. Representative', ''),
('GJ-04', 'Mahesana', 'Gujarat', 'Hon. Representative', ''),
('GJ-05', 'Sabarkantha', 'Gujarat', 'Hon. Representative', ''),
('GJ-06', 'Gandhinagar', 'Gujarat', 'Hon. Representative', ''),
('GJ-07', 'Ahmedabad East', 'Gujarat', 'Hon. Representative', ''),
('GJ-08', 'Ahmedabad West', 'Gujarat', 'Hon. Representative', ''),
('GJ-09', 'Surendranagar', 'Gujarat', 'Hon. Representative', ''),
('GJ-10', 'Rajkot', 'Gujarat', 'Hon. Representative', ''),
('GJ-11', 'Porbandar', 'Gujarat', 'Hon. Representative', ''),
('GJ-12', 'Jamnagar', 'Gujarat', 'Hon. Representative', ''),
('GJ-13', 'Junagadh', 'Gujarat', 'Hon. Representative', ''),
('GJ-14', 'Amreli', 'Gujarat', 'Hon. Representative', ''),
('GJ-15', 'Bhavnagar', 'Gujarat', 'Hon. Representative', ''),
('GJ-16', 'Anand', 'Gujarat', 'Hon. Representative', ''),
('GJ-17', 'Kheda', 'Gujarat', 'Hon. Representative', ''),
('GJ-18', 'Panchmahal', 'Gujarat', 'Hon. Representative', ''),
('GJ-19', 'Dahod', 'Gujarat', 'Hon. Representative', ''),
('GJ-20', 'Vadodara', 'Gujarat', 'Hon. Representative', ''),
('GJ-21', 'Chhota Udaipur', 'Gujarat', 'Hon. Representative', ''),
('GJ-22', 'Bharuch', 'Gujarat', 'Hon. Representative', ''),
('GJ-23', 'Bardoli', 'Gujarat', 'Hon. Representative', ''),
('GJ-24', 'Surat', 'Gujarat', 'Hon. Representative', ''),
('GJ-25', 'Navsari', 'Gujarat', 'Hon. Representative', ''),
('GJ-26', 'Valsad', 'Gujarat', 'Hon. Representative', ''),

-- Haryana (10)
('HR-01', 'Ambala', 'Haryana', 'Hon. Representative', ''),
('HR-02', 'Kurukshetra', 'Haryana', 'Hon. Representative', ''),
('HR-03', 'Sirsa', 'Haryana', 'Hon. Representative', ''),
('HR-04', 'Hisar', 'Haryana', 'Hon. Representative', ''),
('HR-05', 'Karnal', 'Haryana', 'Hon. Representative', ''),
('HR-06', 'Sonipat', 'Haryana', 'Hon. Representative', ''),
('HR-07', 'Rohtak', 'Haryana', 'Hon. Representative', ''),
('HR-08', 'Bhiwani-Mahendragarh', 'Haryana', 'Hon. Representative', ''),
('HR-09', 'Gurgaon', 'Haryana', 'Hon. Representative', ''),
('HR-10', 'Faridabad', 'Haryana', 'Hon. Representative', ''),

-- Himachal Pradesh (4)
('HP-01', 'Kangra', 'Himachal Pradesh', 'Hon. Representative', ''),
('HP-02', 'Mandi', 'Himachal Pradesh', 'Hon. Representative', ''),
('HP-03', 'Hamirpur', 'Himachal Pradesh', 'Hon. Representative', ''),
('HP-04', 'Shimla', 'Himachal Pradesh', 'Hon. Representative', ''),

-- Jharkhand (14)
('JH-01', 'Rajmahal', 'Jharkhand', 'Hon. Representative', ''),
('JH-02', 'Dumka', 'Jharkhand', 'Hon. Representative', ''),
('JH-03', 'Godda', 'Jharkhand', 'Hon. Representative', ''),
('JH-04', 'Chatra', 'Jharkhand', 'Hon. Representative', ''),
('JH-05', 'Koderma', 'Jharkhand', 'Hon. Representative', ''),
('JH-06', 'Giridih', 'Jharkhand', 'Hon. Representative', ''),
('JH-07', 'Dhanbad', 'Jharkhand', 'Hon. Representative', ''),
('JH-08', 'Ranchi', 'Jharkhand', 'Hon. Representative', ''),
('JH-09', 'Jamshedpur', 'Jharkhand', 'Hon. Representative', ''),
('JH-10', 'Singhbhum', 'Jharkhand', 'Hon. Representative', ''),
('JH-11', 'Khunti', 'Jharkhand', 'Hon. Representative', ''),
('JH-12', 'Lohardaga', 'Jharkhand', 'Hon. Representative', ''),
('JH-13', 'Palamu', 'Jharkhand', 'Hon. Representative', ''),
('JH-14', 'Hazaribagh', 'Jharkhand', 'Hon. Representative', ''),

-- Karnataka (28)
('KA-01', 'Bengaluru North', 'Karnataka', 'Hon. Anudeep Yajamanyam', ''),
('KA-02', 'Bengaluru Central', 'Karnataka', 'Hon. Representative', ''),
('KA-03', 'Bengaluru South', 'Karnataka', 'Hon. Representative', ''),
('KA-04', 'Bengaluru Rural', 'Karnataka', 'Hon. Representative', ''),
('KA-05', 'Chikkaballapur', 'Karnataka', 'Hon. Representative', ''),
('KA-06', 'Kolar', 'Karnataka', 'Hon. Representative', ''),
('KA-07', 'Tumakuru', 'Karnataka', 'Hon. Representative', ''),
('KA-08', 'Chitradurga', 'Karnataka', 'Hon. Representative', ''),
('KA-09', 'Davangere', 'Karnataka', 'Hon. Representative', ''),
('KA-10', 'Shivamogga', 'Karnataka', 'Hon. Representative', ''),
('KA-11', 'Udupi Shri Krishna', 'Karnataka', 'Hon. Representative', ''),
('KA-12', 'Dakshina Kannada', 'Karnataka', 'Hon. Representative', ''),
('KA-13', 'Chikmagalur', 'Karnataka', 'Hon. Representative', ''),
('KA-14', 'Hassan', 'Karnataka', 'Hon. Representative', ''),
('KA-15', 'Mysuru', 'Karnataka', 'Hon. Representative', ''),
('KA-16', 'Chamarajanagar', 'Karnataka', 'Hon. Representative', ''),
('KA-17', 'Mandya', 'Karnataka', 'Hon. Representative', ''),
('KA-18', 'Ramanagara', 'Karnataka', 'Hon. Representative', ''),
('KA-19', 'Uttara Kannada', 'Karnataka', 'Hon. Representative', ''),
('KA-20', 'Belagavi', 'Karnataka', 'Hon. Representative', ''),
('KA-21', 'Chikkodi', 'Karnataka', 'Hon. Representative', ''),
('KA-22', 'Bagalkot', 'Karnataka', 'Hon. Representative', ''),
('KA-23', 'Vijayapura', 'Karnataka', 'Hon. Representative', ''),
('KA-24', 'Kalaburagi', 'Karnataka', 'Hon. Representative', ''),
('KA-25', 'Koppal', 'Karnataka', 'Hon. Representative', ''),
('KA-26', 'Raichur', 'Karnataka', 'Hon. Representative', ''),
('KA-27', 'Bidar', 'Karnataka', 'Hon. Representative', ''),
('KA-28', 'Ballari', 'Karnataka', 'Hon. Representative', ''),

-- Kerala (20)
('KL-01', 'Kasaragod', 'Kerala', 'Hon. Representative', ''),
('KL-02', 'Kannur', 'Kerala', 'Hon. Representative', ''),
('KL-03', 'Vatakara', 'Kerala', 'Hon. Representative', ''),
('KL-04', 'Wayanad', 'Kerala', 'Hon. Representative', ''),
('KL-05', 'Kozhikode', 'Kerala', 'Hon. Representative', ''),
('KL-06', 'Malappuram', 'Kerala', 'Hon. Representative', ''),
('KL-07', 'Ponnani', 'Kerala', 'Hon. Representative', ''),
('KL-08', 'Palakkad', 'Kerala', 'Hon. Representative', ''),
('KL-09', 'Alathur', 'Kerala', 'Hon. Representative', ''),
('KL-10', 'Thrissur', 'Kerala', 'Hon. Representative', ''),
('KL-11', 'Chalakkudy', 'Kerala', 'Hon. Representative', ''),
('KL-12', 'Ernakulam', 'Kerala', 'Hon. Representative', ''),
('KL-13', 'Idukki', 'Kerala', 'Hon. Representative', ''),
('KL-14', 'Kottayam', 'Kerala', 'Hon. Representative', ''),
('KL-15', 'Alappuzha', 'Kerala', 'Hon. Representative', ''),
('KL-16', 'Mavelikara', 'Kerala', 'Hon. Representative', ''),
('KL-17', 'Pathanamthitta', 'Kerala', 'Hon. Representative', ''),
('KL-18', 'Kollam', 'Kerala', 'Hon. Representative', ''),
('KL-19', 'Attingal', 'Kerala', 'Hon. Representative', ''),
('KL-20', 'Thiruvananthapuram', 'Kerala', 'Hon. Representative', ''),

-- Madhya Pradesh (29)
('MP-01', 'Morena', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-02', 'Bhind', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-03', 'Gwalior', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-04', 'Guna', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-05', 'Sagar', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-06', 'Tikamgarh', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-07', 'Damoh', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-08', 'Khajuraho', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-09', 'Satna', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-10', 'Rewa', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-11', 'Sidhi', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-12', 'Shahdol', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-13', 'Jabalpur', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-14', 'Mandla', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-15', 'Balaghat', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-16', 'Chhindwara', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-17', 'Narmadapuram', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-18', 'Pathariya', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-19', 'Bhopal', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-20', 'Rajgarh', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-21', 'Dewas', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-22', 'Ujjain', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-23', 'Mandsaur', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-24', 'Ratlam', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-25', 'Dhar', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-26', 'Indore', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-27', 'Khargone', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-28', 'Khandwa', 'Madhya Pradesh', 'Hon. Representative', ''),
('MP-29', 'Betul', 'Madhya Pradesh', 'Hon. Representative', ''),

-- Maharashtra (48)
('MH-01', 'Pune North', 'Maharashtra', 'Hon. Representative', ''),
('MH-02', 'Mumbai South', 'Maharashtra', 'Hon. Representative', ''),
('MH-03', 'Mumbai South Central', 'Maharashtra', 'Hon. Representative', ''),
('MH-04', 'Mumbai North Central', 'Maharashtra', 'Hon. Representative', ''),
('MH-05', 'Mumbai North West', 'Maharashtra', 'Hon. Representative', ''),
('MH-06', 'Mumbai North', 'Maharashtra', 'Hon. Representative', ''),
('MH-07', 'Thane', 'Maharashtra', 'Hon. Representative', ''),
('MH-08', 'Kalyan', 'Maharashtra', 'Hon. Representative', ''),
('MH-09', 'Palghar', 'Maharashtra', 'Hon. Representative', ''),
('MH-10', 'Bhiwandi', 'Maharashtra', 'Hon. Representative', ''),
('MH-11', 'Raigad', 'Maharashtra', 'Hon. Representative', ''),
('MH-12', 'Maval', 'Maharashtra', 'Hon. Representative', ''),
('MH-13', 'Pune', 'Maharashtra', 'Hon. Representative', ''),
('MH-14', 'Baramati', 'Maharashtra', 'Hon. Representative', ''),
('MH-15', 'Shirur', 'Maharashtra', 'Hon. Representative', ''),
('MH-16', 'Ahmednagar', 'Maharashtra', 'Hon. Representative', ''),
('MH-17', 'Shirdi', 'Maharashtra', 'Hon. Representative', ''),
('MH-18', 'Beed', 'Maharashtra', 'Hon. Representative', ''),
('MH-19', 'Osmanabad', 'Maharashtra', 'Hon. Representative', ''),
('MH-20', 'Latur', 'Maharashtra', 'Hon. Representative', ''),
('MH-21', 'Solapur', 'Maharashtra', 'Hon. Representative', ''),
('MH-22', 'Madha', 'Maharashtra', 'Hon. Representative', ''),
('MH-23', 'Sangli', 'Maharashtra', 'Hon. Representative', ''),
('MH-24', 'Satara', 'Maharashtra', 'Hon. Representative', ''),
('MH-25', 'Ratnagiri-Sindhudurg', 'Maharashtra', 'Hon. Representative', ''),
('MH-26', 'Kolhapur', 'Maharashtra', 'Hon. Representative', ''),
('MH-27', 'Hatkanangle', 'Maharashtra', 'Hon. Representative', ''),
('MH-28', 'Nashik', 'Maharashtra', 'Hon. Representative', ''),
('MH-29', 'Dindori', 'Maharashtra', 'Hon. Representative', ''),
('MH-30', 'Dhule', 'Maharashtra', 'Hon. Representative', ''),
('MH-31', 'Nandurbar', 'Maharashtra', 'Hon. Representative', ''),
('MH-32', 'Jalgaon', 'Maharashtra', 'Hon. Representative', ''),
('MH-33', 'Raver', 'Maharashtra', 'Hon. Representative', ''),
('MH-34', 'Buldhana', 'Maharashtra', 'Hon. Representative', ''),
('MH-35', 'Akola', 'Maharashtra', 'Hon. Representative', ''),
('MH-36', 'Amravati', 'Maharashtra', 'Hon. Representative', ''),
('MH-37', 'Wardha', 'Maharashtra', 'Hon. Representative', ''),
('MH-38', 'Ramtek', 'Maharashtra', 'Hon. Representative', ''),
('MH-39', 'Nagpur', 'Maharashtra', 'Hon. Representative', ''),
('MH-40', 'Bhandara-Gondiya', 'Maharashtra', 'Hon. Representative', ''),
('MH-41', 'Gadchiroli-Chimur', 'Maharashtra', 'Hon. Representative', ''),
('MH-42', 'Chandrapur', 'Maharashtra', 'Hon. Representative', ''),
('MH-43', 'Yavatmal-Washim', 'Maharashtra', 'Hon. Representative', ''),
('MH-44', 'Hingoli', 'Maharashtra', 'Hon. Representative', ''),
('MH-45', 'Nanded', 'Maharashtra', 'Hon. Representative', ''),
('MH-46', 'Parbhani', 'Maharashtra', 'Hon. Representative', ''),
('MH-47', 'Jalna', 'Maharashtra', 'Hon. Representative', ''),
('MH-48', 'Aurangabad', 'Maharashtra', 'Hon. Representative', ''),

-- Tamil Nadu (39)
('TN-01', 'Chennai North', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-02', 'Chennai South', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-03', 'Chennai Central', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-04', 'Sriperumbudur', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-05', 'Kancheepuram', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-06', 'Arakkonam', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-07', 'Vellore', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-08', 'Krishnagiri', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-09', 'Dharmapuri', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-10', 'Tiruvannamalai', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-11', 'Arani', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-12', 'Viluppuram', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-13', 'Kallakurichi', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-14', 'Salem', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-15', 'Namakkal', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-16', 'Erode', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-17', 'Tiruppur', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-18', 'Nilgiris', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-19', 'Coimbatore', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-20', 'Pollachi', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-21', 'Dindigul', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-22', 'Karur', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-23', 'Tiruchirappalli', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-24', 'Perambalur', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-25', 'Cuddalore', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-26', 'Chidambaram', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-27', 'Mayiladuthurai', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-28', 'Nagapattinam', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-29', 'Thanjavur', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-30', 'Sivaganga', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-31', 'Madurai', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-32', 'Theni', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-33', 'Virudhunagar', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-34', 'Ramanathapuram', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-35', 'Thoothukudi', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-36', 'Tenkasi', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-37', 'Tirunelveli', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-38', 'Kanniyakumari', 'Tamil Nadu', 'Hon. Representative', ''),
('TN-39', 'Dharmapuri', 'Tamil Nadu', 'Hon. Representative', ''),

-- Uttar Pradesh (80)
('UP-01', 'Saharanpur', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-02', 'Kairana', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-03', 'Muzaffarnagar', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-04', 'Bijnor', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-05', 'Nagina', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-06', 'Moradabad', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-07', 'Rampur', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-08', 'Sambhal', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-09', 'Amroha', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-10', 'Meerut', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-11', 'Baghpat', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-12', 'Ghaziabad', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-13', 'Gautam Buddha Nagar', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-14', 'Bulandshahr', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-15', 'Aligarh', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-16', 'Hathras', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-17', 'Mathura', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-18', 'Agra', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-19', 'Firozabad', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-20', 'Mainpuri', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-21', 'Etah', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-22', 'Badaun', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-23', 'Aonla', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-24', 'Bareilly', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-25', 'Pilibhit', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-26', 'Shahjahanpur', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-27', 'Kheri', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-28', 'Dhaurahra', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-29', 'Sitapur', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-30', 'Hardoi', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-31', 'Misrikh', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-32', 'Unnao', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-33', 'Mohanlalganj', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-34', 'Lucknow', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-35', 'Rae Bareli', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-36', 'Amethi', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-37', 'Sultanpur', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-38', 'Pratapgarh', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-39', 'Farrukhabad', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-40', 'Etawah', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-41', 'Kannauj', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-42', 'Kanpur', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-43', 'Akbarpur', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-44', 'Jalaun', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-45', 'Jhansi', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-46', 'Hamirpur', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-47', 'Banda', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-48', 'Fatehpur', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-49', 'Kaushambi', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-50', 'Phulpur', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-51', 'Allahabad', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-52', 'Barabanki', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-53', 'Faizabad', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-54', 'Ambedkar Nagar', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-55', 'Bahraich', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-56', 'Kaiserganj', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-57', 'Shravasti', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-58', 'Gonda', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-59', 'Domariyaganj', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-60', 'Basti', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-61', 'Sant Kabir Nagar', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-62', 'Maharajganj', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-63', 'Gorakhpur', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-64', 'Kushi Nagar', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-65', 'Deoria', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-66', 'Bansgaon', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-67', 'Lalganj', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-68', 'Azamgarh', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-69', 'Ghosi', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-70', 'Salempur', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-71', 'Ballia', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-72', 'Jaunpur', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-73', 'Machhlishahr', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-74', 'Ghazipur', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-75', 'Chandauli', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-76', 'Varanasi', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-77', 'Bhadohi', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-78', 'Mirzapur', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-79', 'Robertsganj', 'Uttar Pradesh', 'Hon. Representative', ''),
('UP-80', 'Karchhana', 'Uttar Pradesh', 'Hon. Representative', ''),

-- West Bengal (42)
('WB-01', 'Cooch Behar', 'West Bengal', 'Hon. Representative', ''),
('WB-02', 'Alipurduars', 'West Bengal', 'Hon. Representative', ''),
('WB-03', 'Jalpaiguri', 'West Bengal', 'Hon. Representative', ''),
('WB-04', 'Darjeeling', 'West Bengal', 'Hon. Representative', ''),
('WB-05', 'Raiganj', 'West Bengal', 'Hon. Representative', ''),
('WB-06', 'Balurghat', 'West Bengal', 'Hon. Representative', ''),
('WB-07', 'Maldaha Uttar', 'West Bengal', 'Hon. Representative', ''),
('WB-08', 'Maldaha Dakshin', 'West Bengal', 'Hon. Representative', ''),
('WB-09', 'Jangipur', 'West Bengal', 'Hon. Representative', ''),
('WB-10', 'Baharampur', 'West Bengal', 'Hon. Representative', ''),
('WB-11', 'Murshidabad', 'West Bengal', 'Hon. Representative', ''),
('WB-12', 'Krishnanagar', 'West Bengal', 'Hon. Representative', ''),
('WB-13', 'Ranaghat', 'West Bengal', 'Hon. Representative', ''),
('WB-14', 'Bangaon', 'West Bengal', 'Hon. Representative', ''),
('WB-15', 'Barrackpur', 'West Bengal', 'Hon. Representative', ''),
('WB-16', 'Dum Dum', 'West Bengal', 'Hon. Representative', ''),
('WB-17', 'Barasat', 'West Bengal', 'Hon. Representative', ''),
('WB-18', 'Basirhat', 'West Bengal', 'Hon. Representative', ''),
('WB-19', 'Jaynagar', 'West Bengal', 'Hon. Representative', ''),
('WB-20', 'Mathurapur', 'West Bengal', 'Hon. Representative', ''),
('WB-21', 'Diamond Harbour', 'West Bengal', 'Hon. Representative', ''),
('WB-22', 'Jadavpur', 'West Bengal', 'Hon. Representative', ''),
('WB-23', 'Kolkata Dakshin', 'West Bengal', 'Hon. Representative', ''),
('WB-24', 'Kolkata Uttar', 'West Bengal', 'Hon. Representative', ''),
('WB-25', 'Howrah', 'West Bengal', 'Hon. Representative', ''),
('WB-26', 'Uluberia', 'West Bengal', 'Hon. Representative', ''),
('WB-27', 'Sreerampur', 'West Bengal', 'Hon. Representative', ''),
('WB-28', 'Hooghly', 'West Bengal', 'Hon. Representative', ''),
('WB-29', 'Arambagh', 'West Bengal', 'Hon. Representative', ''),
('WB-30', 'Tamluk', 'West Bengal', 'Hon. Representative', ''),
('WB-31', 'Kanthi', 'West Bengal', 'Hon. Representative', ''),
('WB-32', 'Ghatal', 'West Bengal', 'Hon. Representative', ''),
('WB-33', 'Jhargram', 'West Bengal', 'Hon. Representative', ''),
('WB-34', 'Medinipur', 'West Bengal', 'Hon. Representative', ''),
('WB-35', 'Purulia', 'West Bengal', 'Hon. Representative', ''),
('WB-36', 'Bankura', 'West Bengal', 'Hon. Representative', ''),
('WB-37', 'Bishnupur', 'West Bengal', 'Hon. Representative', ''),
('WB-38', 'Bardhaman Purba', 'West Bengal', 'Hon. Representative', ''),
('WB-39', 'Bardhaman-Durgapur', 'West Bengal', 'Hon. Representative', ''),
('WB-40', 'Asansol', 'West Bengal', 'Hon. Representative', ''),
('WB-41', 'Bolpur', 'West Bengal', 'Hon. Representative', ''),
('WB-42', 'Birbhum', 'West Bengal', 'Hon. Representative', ''),

-- Delhi (7)
('DL-01', 'New Delhi Central', 'Delhi', 'Hon. Representative', ''),
('DL-02', 'Chandni Chowk', 'Delhi', 'Hon. Representative', ''),
('DL-03', 'North East Delhi', 'Delhi', 'Hon. Representative', ''),
('DL-04', 'East Delhi', 'Delhi', 'Hon. Representative', ''),
('DL-05', 'North West Delhi', 'Delhi', 'Hon. Representative', ''),
('DL-06', 'West Delhi', 'Delhi', 'Hon. Representative', ''),
('DL-07', 'South Delhi', 'Delhi', 'Hon. Representative', '');
